networks:
  frontend:
  backend:

services:
  web1:
    image: nginx:${APP_VERSION}
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./web1:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  web2:
    image: nginx:${APP_VERSION}
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - backend
  proxy:
    image: nginx:${APP_VERSION}
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
  
  #testeapp:
  #  image: ubuntu
  #  command: ["bash", "-c", "while true; do sleep 30; done"]
  #  restart: unless-stopped
